services:
    api:
        build: ./api_server
        volumes:
            - ./api_server/src:/root/api_server
        tty: true
        restart: always
    sikaku_nginx:
        restart: always
        image: nginx:latest
        container_name: sikaku_nginx
        ports:
            - "8442:80"
        volumes:
            # NGINXのコンフィグファイルをホストOSから、ゲストOSに連結する
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/keys:/etc/nginx/keys
            - ./nginx/statics:/etc/nginx/static/statics
        tty: true
    