FROM python:3.10.13-slim

WORKDIR /root/api_server

RUN pip install --upgrade pip
RUN pip install beautifulsoup4
RUN pip install cachecontrol[filecache]
RUN pip install PyMuPDF
RUN pip install requests
RUN pip install fastapi
RUN pip install gunicorn
RUN pip install python-dotenv
RUN pip install appwrite

COPY ./src .

CMD ["gunicorn","-k","uvicorn.workers.UvicornWorker ","api_server:app","--preload","--bind","0.0.0.0:3001"]
# gunicorn -k uvicorn.workers.UvicornWorker api_server:app --preload --bind 0.0.0.0:3001